---
title: "Formula 1 data analysis"
author: "Andreas Svenningsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = F)
```

# Packages
```{r}
library(tidyverse)
library(lubridate)
library(plotly)
library(shiny)
library(glue)
```


# Importing data

```{r}

loadData <- function(race) {return(read_csv(glue("Data/{race}_Race_laps.csv"), show_col_types = F))}


```

```{r}
df <- loadData("SPAIN")
subset(df, DriverNumber == 1)


```


```{r}

races <- c("BAHRAIN", "SAUDI", "AUSTRALIA", "BAKU","MIAMI","MONACO", "SPAIN")

cat("Columns:\n", colnames(df), "\n\n")

driver.names <- unique(df$Driver)
cat("Drivers:\n", driver.names, "\n\n")

driver.nr <- unique(df$DriverNumber)
cat("Driver nr:\n", driver.nr, "\n\n")

```


```{r}

convertLapTimes <- function(df) {
  laptimes <- c()
  for (i in 1:length(df$LapTime)) {
    laptime <- gsub("0 days 00:","", df$LapTime[i])
    laptimes <- c(laptimes, as.numeric(ms(laptime)))
    }
  df$LapTime <- laptimes
  return(df)
}

laps <- df %>% drop_na(LapTime) %>% convertLapTimes(.)

removePitLaps <- function(df) {return(subset(df, is.na(PitOutTime)) %>% subset(., is.na(PitInTime)))}

removeLapsTrackStatus <- function(df) {return(subset(df, TrackStatus == 1))}

laps.nonpit <- removePitLaps(laps)
laps.nonpit.greenflag <- removeLapsTrackStatus(laps.nonpit)


```

```{r}
# Get pit time data

onlyPitLaps <- function(df) {
  status <- c(1,2,3,4,6,7, 25, 45) # Used for TrackStatus

  selected_laps_pit <- 
    subset(df, !is.na(PitOutTime) | !is.na(PitInTime)) %>% 
    subset(., (LapNumber == 1 & !is.na(PitInTime) | LapNumber != 1)) %>%
    subset(., TrackStatus %in% status)
  
  
  pit_drivers <- c()
  pit_times <- c()
  
  for (i in seq(1,length(selected_laps_pit$PitInTime)-1,by = 2)) {
    time_diff <- as.numeric(
      as.duration(
        hms(gsub("0 days ", "", selected_laps_pit$PitOutTime[i+1])) - 
        hms(gsub("0 days ", "", selected_laps_pit$PitInTime[i]))
        )
      )
    if (is.na(time_diff)) {next}
    if (time_diff > 80) {next}
    else {
      pit_times <- c(pit_times, time_diff)  
      pit_drivers <- c(pit_drivers, selected_laps_pit$Driver[i])
    }
  }
  
  pit_data <- data.frame(Driver = pit_drivers, PitTime = pit_times )
  return(pit_data)
}


data <- loadData("MIAMI")
laps <- data %>% drop_na(LapTime) %>% convertLapTimes(.)
laps.nonpit <- removePitLaps(laps)
laps.nonpit.greenflag <- removeLapsTrackStatus(laps.nonpit)
pit_data <- onlyPitLaps(data)
pit_data

```


```{r}
# Total width of window is 12 units

ui <- fluidPage(
  titlePanel(h1("F1 data visualisation for selected 2023 grand prix's!", align = "center")),
  theme = "flatly",
  sidebarLayout(position = "left",
                sidebarPanel("Choose driver", width = 2, 
                             selectInput(inputId = "driverSelect", 
                                         label = "Selected drivers:", 
                                         choices = driver.names, 
                                         selected = c("VER", "HAM"), 
                                         multiple = T),
                             selectInput(inputId = "GPSelect",
                                         label = "Selected grand prix",
                                         choices = races, 
                                         selected = "SPAIN",
                                         multiple = F)
                             ),
                mainPanel(width = 9,
                          fluidRow(
                            splitLayout(cellWidths = c("50%","50%"),
                                        plotlyOutput(outputId = "scatter"),
                                        plotlyOutput(outputId = "boxplot")
                                        )
                            ),
                          fluidRow(
                            plotlyOutput(outputId = "lineplot")  
                          )
                          
                )
))

server <- function(input, output) {
  
  # Manage data
  selected_drivers <- reactive(input$driverSelect)
  selected_gp <- reactive(input$GPSelect)
  
  data <- reactive(loadData(selected_gp()))
  
  laps <- reactive(data() %>% drop_na(LapTime) %>% convertLapTimes(.))
  laps.nonpit <- reactive(removePitLaps(laps()))
  laps.nonpit.greenflag <- reactive(removeLapsTrackStatus(laps.nonpit()))
  pit_data <- reactive(onlyPitLaps(data()))
  
  selected_data <- reactive(subset(laps.nonpit.greenflag(), Driver %in% selected_drivers()))

  selected_pit_data <- reactive(subset(pit_data(), Driver %in% selected_drivers()))
  
  # Create interactive plots
  # Laptime vs lapnumber
  pt1 <- reactive({
    p1 <- ggplot(selected_data(), aes(LapNumber, LapTime, col = Driver)) + 
      geom_line() + 
      geom_point() + 
      xlab("Lap Number") + 
      ylab("Lap time [s]") + 
      ggtitle("Lap time throughout the race for selected drivers")
    ggplotly(p1) %>% layout(showlegend = F) 
  })
  
  # Boxplot of laptimes
  pt2 <- reactive({
    p2 <- ggplot(selected_data(), mapping = 
                   aes(x = reorder(Driver, LapTime, FUN = median), y = LapTime, col = Driver)) + 
      geom_boxplot() + 
      xlab("Driver") + 
      ylab("Lap time [s]") + 
      ggtitle("Lap time distributions for selected drivers") + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    ggplotly(p2) %>% layout(showlegend = F)
  })
  
  # Scatterplot of drivers vs pit times
  pt3 <- reactive({
    p3 <- ggplot(data = selected_pit_data()) + 
      geom_point(mapping = aes(PitTime, Driver, col = Driver), size = 3) + 
      xlab("Pit Time [s]") + 
      ylab("Driver") + 
      ggtitle("Pit times for selected drivers", 
              subtitle = "Only shows drivers who pitted during non red flags")
    
    ggplotly(p3) %>% layout(showlegend = F)
  })


  # Render plots
  output$lineplot <- renderPlotly({pt1()})
  output$boxplot  <- renderPlotly({pt2()})
  output$scatter  <- renderPlotly({pt3()})
}

shinyApp(ui, server)
```


